### ISSUE TITLE
Emulator : SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by merri-ment** [invertase/stripe-firebase-extensions#581]
# Bug report

- Extension name: `invertase/firestore-stripe-payments@0.3.6`

## Describe the bug

In the Firebase Emulator locally, i encounter the following error when the function createCustomer is run;
```
functions: Failed to initialize and load triggers. This shouldn't happen: await is only valid in async functions and the top level bodies of modules
⚠  Your function was killed because it raised an unhandled error.
⚠  /Users/me/.cache/firebase/extensions/invertase/firestore-stripe-payments@0.3.6/functions/lib/index.js:50
const subscription = await stripe.subscriptions.retrieve(subscriptionId, {
                     ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at loadTriggers (/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:584:25)
    at main (/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:637:32)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
⚠  functions: Failed to initialize and load triggers. This shouldn't happen: await is only valid in async functions and the top level bodies of modules
⚠  Your function was killed because it raised an unhandled error.
⬢  functions: Failed to handle request for function us-central1-ext-firestore-stripe-payments-createCustomer
```
I have tried running different node versions 16 and 18, that did not help. 
I'm reluctant to edit the source file and wrap the await in a async func.

The only thing that resolved the issue was to downgrade to "stripe/firestore-stripe-payments@0.3.2".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Spin up Sprite CI - `stripe listen --api-key rk_test_*********** --forward-to http://127.0.0.1:5001/{project-name}/{firebase-server}/ext-firestore-stripe-payments-handleWebhookEvents `
2. Spin up Firebase Emulator CI - `firebase emulators:start --project={project-name}`
3. Spin up my app - `npm run dev`
4. Save a product in my Sprite developer admin Test-Mode environment 

By saving a Product the 'product.updated' event will be trigger from Sprite and received by the invertase/firestore-stripe-payments Extension, where it fails.

**Comment by merri-ment** [comment]
One of the error suggestions is to - run "npm run build" in your functions directory. I set node to 14 as per the package.json and ran build in firebase/extensions/invertase/firestore-stripe-payments@0.3.6/functions, but quite a few errors broke the build.

```

npm run build                     

> firestore-stripe-payments@ build /Users/me/.cache/firebase/extensions/invertase/firestore-stripe-payments@0.3.6/functions
> npm run clean && tsc


> firestore-stripe-payments@ clean /Users/me/.cache/firebase/extensions/invertase/firestore-stripe-payments@0.3.6/functions
> rimraf lib

src/index.ts:1:5 - error TS1128: Declaration or statement expected.

1     .collection(config.customersCollectionPath)
      ~

src/index.ts:111:1 - error TS1128: Declaration or statement expected.

111 };
    ~

src/index.ts:969:1 - error TS1005: '}' expected.

969 
    

  src/index.ts:965:21
    965 ): Promise<void> => {
                            ~
    The parser expected to find a '}' to match the '{' token here.


Found 3 errors in the same file, starting at: src/index.ts:1```
