### ISSUE TITLE
invoice.upcoming failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

### ISSUE THREAD

**Issue by joelc0193** [invertase/stripe-firebase-extensions#616]
# Bug report

firestore-stripe-payments

## Describe the bug

This was the error:

> Stripe event of type [invoice.upcoming] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string."

This is the request:

```
{
  "id": ["evt_1OuHWvGLpWnCiB3YultsM9NG"](https://dashboard.stripe.com/events/evt_1OuHWvGLpWnCiB3YultsM9NG),
  "object": "event",
  "api_version": "2022-11-15",
  "created": 1710435201,
  "data": {
    "object": {
      "object": "invoice",
      "account_country": "US",
      "account_name": "Poster Fans LLC",
      "account_tax_ids": null,
      "amount_due": 1000,
      "amount_paid": 0,
      "amount_remaining": 1000,
      "amount_shipping": 0,
      "application": null,
      "application_fee_amount": null,
      "attempt_count": 0,
      "attempted": false,
      "automatic_tax": {
        "enabled": false,
        "liability": null,
        "status": null
      },
      "billing_reason": "upcoming",
      "charge": null,
      "collection_method": "charge_automatically",
      "created": 1711039978,
      "currency": "usd",
      "custom_fields": null,
      "customer": ["cus_PPWc0hdWkEmlzD"](https://dashboard.stripe.com/customers/cus_PPWc0hdWkEmlzD),
      "customer_address": null,
      "customer_email": "info@managedmusic.com",
      "customer_name": null,
      "customer_phone": null,
      "customer_shipping": null,
      "customer_tax_exempt": "none",
      "customer_tax_ids": [
      ],
      "default_payment_method": null,
      "default_source": null,
      "default_tax_rates": [
      ],
      "description": null,
      "discount": null,
      "discounts": [
      ],
      "due_date": null,
      "effective_at": null,
      "ending_balance": 0,
      "footer": null,
      "from_invoice": null,
      "issuer": {
        "type": "self"
      },
      "last_finalization_error": null,
      "latest_revision": null,
      "lines": {
        "object": "list",
        "data": [
          {
            "id": ["il_tmp_125151GLpWnCiB3Y1403fe62"](https://dashboard.stripe.com/subscriptions/il_tmp_125151GLpWnCiB3Y1403fe62),
            "object": "line_item",
            "amount": 1000,
            "amount_excluding_tax": 1000,
            "currency": "usd",
            "description": "1 × Dealer Membership (at $10.00 / month)",
            "discount_amounts": [
            ],
            "discountable": true,
            "discounts": [
            ],
            "invoice": null,
            "livemode": true,
            "metadata": {
            },
            "period": {
              "end": 1713718378,
              "start": 1711039978
            },
            "plan": {
              "id": ["price_1OFdYZGLpWnCiB3YAWTsq1R6"](https://dashboard.stripe.com/prices/price_1OFdYZGLpWnCiB3YAWTsq1R6),
              "object": "plan",
              "active": true,
              "aggregate_usage": null,
              "amount": 1000,
              "amount_decimal": "1000",
              "billing_scheme": "per_unit",
              "created": 1700748423,
              "currency": "usd",
              "interval": "month",
              "interval_count": 1,
              "livemode": true,
              "metadata": {
              },
              "nickname": null,
              "product": ["prod_P3l46ip1uGjUaM"](https://dashboard.stripe.com/products/prod_P3l46ip1uGjUaM),
              "tiers_mode": null,
              "transform_usage": null,
              "trial_period_days": null,
              "usage_type": "licensed"
            },
            "price": {
              "id": ["price_1OFdYZGLpWnCiB3YAWTsq1R6"](https://dashboard.stripe.com/prices/price_1OFdYZGLpWnCiB3YAWTsq1R6),
              "object": "price",
              "active": true,
              "billing_scheme": "per_unit",
              "created": 1700748423,
              "currency": "usd",
              "custom_unit_amount": null,
              "livemode": true,
              "lookup_key": null,
              "metadata": {
              },
              "nickname": null,
              "product": ["prod_P3l46ip1uGjUaM"](https://dashboard.stripe.com/products/prod_P3l46ip1uGjUaM),
              "recurring": {
                "aggregate_usage": null,
                "interval": "month",
                "interval_count": 1,
                "trial_period_days": null,
                "usage_type": "licensed"
              },
              "tax_behavior": "unspecified",
              "tiers_mode": null,
              "transform_quantity": null,
              "type": "recurring",
              "unit_amount": 1000,
              "unit_amount_decimal": "1000"
            },
            "proration": false,
            "proration_details": {
              "credited_items": null
            },
            "quantity": 1,
            "subscription": ["sub_1Ob4GUGLpWnCiB3YyYFwnBqd"](https://dashboard.stripe.com/subscriptions/sub_1Ob4GUGLpWnCiB3YyYFwnBqd),
            "subscription_item": "si_PPu4h18lzBJHnq",
            "tax_amounts": [
            ],
            "tax_rates": [
            ],
            "type": "subscription",
            "unit_amount_excluding_tax": "1000"
          }
        ],
        "has_more": false,
        "total_count": 1,
        "url": "/v1/invoices/upcoming/lines?customer=cus_PPWc0hdWkEmlzD&subscription=sub_1Ob4GUGLpWnCiB3YyYFwnBqd"
      },
      "livemode": true,
      "metadata": {
      },
      "next_payment_attempt": 1711043578,
      "number": null,
      "on_behalf_of": null,
      "paid": false,
      "paid_out_of_band": false,
      "payment_intent": null,
      "payment_settings": {
        "default_mandate": null,
        "payment_method_options": null,
        "payment_method_types": null
      },
      "period_end": 1711039978,
      "period_start": 1708534378,
      "post_payment_credit_notes_amount": 0,
      "pre_payment_credit_notes_amount": 0,
      "quote": null,
      "receipt_number": null,
      "rendering": null,
      "rendering_options": null,
      "shipping_cost": null,
      "shipping_details": null,
      "starting_balance": 0,
      "statement_descriptor": null,
      "status": "draft",
      "status_transitions": {
        "finalized_at": null,
        "marked_uncollectible_at": null,
        "paid_at": null,
        "voided_at": null
      },
      "subscription": ["sub_1Ob4GUGLpWnCiB3YyYFwnBqd"](https://dashboard.stripe.com/subscriptions/sub_1Ob4GUGLpWnCiB3YyYFwnBqd),
      "subscription_details": {
        "metadata": {
        }
      },
      "subtotal": 1000,
      "subtotal_excluding_tax": 1000,
      "tax": null,
      "test_clock": null,
      "total": 1000,
      "total_discount_amounts": [
      ],
      "total_excluding_tax": 1000,
      "total_tax_amounts": [
      ],
      "transfer_data": null,
      "webhooks_delivered_at": null
    }
  },
  "livemode": true,
  "pending_webhooks": 1,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "invoice.upcoming"
}

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

## Additional context

Add any other context about the problem here.

```

**Comment by jsteele-stripe** [comment]
cc @dackers86

**Comment by hasan-abul** [comment]
@aar-stripe By default stripe don't have an id or payment intent for invoice.upcoming event. Do we have a solution here? Thanks

**Comment by aar-stripe** [comment]
unfortunately until the maintainers fix the issue you can't really do much.

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by SohelIslamImran** [comment]
![image](https://github.com/invertase/stripe-firebase-extensions/assets/76745339/664ac1e2-bf80-40e9-9b33-13cfde63033a)

**Comment by maztak** [comment]
Same here. Is there any updates?

**Comment by maztak** [comment]
I didn't install Send Invoices using Stripe extension.
https://extensions.dev/extensions/invertase/firestore-stripe-invoices

**Comment by celso0** [comment]
I have the same issue with [invoice.paid] events. The Google Cloud logs for the extension show this:

{
  "textPayload": "❗️[Error]: Webhook handler for  Stripe event [evt_1RPVrhFfOYKHacY1o2nSubao] of type [invoice.paid] failed: Value for argument \"documentPath\" is not a valid resource path. Path must be a non-empty string.",
  "insertId": "6827aeeb000eb5e71a817e23",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "function_name": "ext-firestore-stripe-payments-handleWebhookEvents",
      "project_id": "xxx-xxxx"
    }
  },
  "timestamp": "2025-05-16T21:32:27.964071Z",
  "severity": "ERROR",
  "labels": {
    "instance_id": "007f65c6d2364355dd3e92ac0b4d6ab7dbc02f0bf23d5a544c218f8d4ef9e08145d820bf03028f84536369ea4477898279c7ffee3f73ba05c257254b9613f8659bd2d4e9e16df20da3545b74d87229",
    "execution_id": "5o0ou5ktj00p",
    "runtime_version": "nodejs20_20250503_20_19_1_RC00"
  },
  "logName": "projects/xxx-xxxx/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/xxx-xxxx/traces/d4bd5337c0c1dffec7e8e8b66dfab989",
  "receiveTimestamp": "2025-05-16T21:32:28.014006117Z"
}

**Comment by nickycdk** [comment]
@cabljac What is the status of this? I am experiencing same issue in https://github.com/invertase/stripe-firebase-extensions/issues/701

**Comment by nickycdk** [comment]
@celso0 @maztak - Any updates on what you have done in your end? Seems like a quite critical error, as the Firebase extension isn't correctly syncing the subscription status to the Firestore database or Firebase Authentication custom claims.

**Comment by cabljac** [comment]
Hi all, ill see about prioritising this next week, hopefully to try and resolve ASAP.

Thanks for your patience!

**Comment by ebenbruyns** [comment]
I have the same issue, I'm also seeing some subscriptions not updating properly before I can read them. Before I dig deeper into that is that related to this?

**Comment by chrisj74** [comment]
any update on this? PR seems waiting on review, so 🤞can be done soon.

**Comment by romain-pattyn** [comment]
Any update? Seems like a quite critical error. Extension never syncs the invoices => 
```
ext-firestore-stripe-payments-handleWebhookEvents1j7p0issebty Error: ❗️[Error]: Webhook handler for  Stripe event [evt_...] of type [invoice.payment_succeeded] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:133:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:120:11)
    at Object.webhookHandlerError (/workspace/lib/logs.js:85:33)
    at /workspace/lib/index.js:257:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

**Comment by jimmykane** [comment]
@cabljac  guys is this maintained or what. WE are at the age of AI and this should the heck trivial.

**Comment by jimmykane** [comment]
Well this looks like a misconfiguration from the frontend to the extension.  

> Here is what is happening under the hood:
> 
> The Extension's "Shortcut": To be efficient (and cheaper), the extension tries to avoid making extra API calls to Stripe. When it receives an invoice.paid event, it hopes to find the firebaseUID right there in the event payload (in the metadata).
> 
> The "Gap" in Stripe: Stripe does not automatically copy metadata from a Customer to their Invoices or Subscriptions. You have to explicitly tell it to do so at creation time.
> 
> The Failure Mode: Because your client-side code didn't explicitly put the metadata on the subscription_data, the Invoice arrived empty. The extension looked for metadata.firebaseUID, found nothing, and instead of gracefully saying "I can't match this user" or "Let me fetch the Customer object to double-check", it tried to use an empty value in a path string and crashed.


We solved it via for example 

```
            const sessionPayload: any = {
                price: priceId,
                success_url: success,
                cancel_url: cancel,
                allow_promotion_codes: true,
                mode: mode, // Explicitly set mode
                metadata: {
                    firebaseUID: user.uid
                }
            };

            if (mode === 'subscription') {
                sessionPayload.subscription_data = {
                    metadata: {
                        firebaseUID: user.uid
                    }
                };
            }
```
