### ISSUE TITLE
migrate to @caiyongji/firestore-stripe-payments

### ISSUE THREAD

**Issue by caiyongji** [invertase/stripe-firebase-extensions#624]
This is because this repo using outdated firebase. As no one maintains this project, i've created new one [@caiyongji/firestore-stripe-payments](https://www.npmjs.com/package/@caiyongji/firestore-stripe-payments).

```
npm i @caiyongji/firestore-stripe-payments
```

**Comment by davie-robertson** [comment]
I've lost at least a day of effort because of the old firebase dependencies breaking my code when updating firebase and then getting errors such as 
```
Error: Component analytics has not been registered yet
    at Provider.initialize (provider.ts:239:13)
    at initializeAnalytics (api.ts:112:47)
    at getAnalytics (api.ts:85:10)
    at firebase-app.ts:32:19```

**Comment by KoTanukiKyoso** [comment]
非常にありがたいです。
ところで、Firebase 11ではエラーが出ます
10.14.1あたりでは動作するようです

**Comment by cabljac** [comment]
Hey! I appreciate this repo has been inactive for ages. As a developer myself, I also appreciate your effort of publishing a fork for people to use.

I've just released a new version of the @invertase scoped package, and we now have some dedicated resource for maintenance on this repo.

Closing this issue. Thanks!
